version: 2.1
orbs: #packages
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 #allows us to use docker orb's commands
jobs: 
  build: 
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows: 
  simple_workflow:
    jobs:
      - build #1st job
      - test: #2nd job
          requires:
            - build
